{{ if (eq .Values.kafkaMode "kraft") }}
{{ $clusterName := include "kafka-operator-resources.fullname" . }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ $clusterName }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.Kafka.spec.kafka.version }}
    metadataVersion: {{ .Values.Kafka.spec.kafka.metadataVersion }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        {{- if .Values.networkPolicyPeers }}
        networkPolicyPeers:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
              strimzi.io/kind: Kafka
        {{ if ( .Values.kafkaBridge.enabled ) }}
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ $clusterName }}
              strimzi.io/kind: KafkaBridge
        {{- end }}
          {{- with .Values.networkPolicyPeers }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
        {{- end }}
      - name: tls
        port: 9093
        type: internal
        tls: true
    {{- if .Values.Kafka.listeners.external }}
      - name: {{ .Values.Kafka.listeners.external.name }}
        port:  {{ .Values.Kafka.listeners.external.port }}
        type: internal
        tls: {{ .Values.Kafka.listeners.external.tls }}
        configuration:
          brokers:
          {{- range $i, $e := until (int .Values.KafkaNodePool.replicas) }}
            - broker: {{ $i }}
              advertisedHost: localhost
              advertisedPort:  {{ $.Values.Kafka.listeners.external.port }}
          {{- end }}
      {{- end }}
  config:
    {{- with .Values.Kafka.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}

