{{ if ( .Values.kafkaBridge.enabled ) }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: {{ .Release.Name }}
spec:
  bootstrapServers:  {{ .Release.Name }}-kafka-bootstrap:9092
  http:
      port: 8080
{{- end }}

