apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workflow-management.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "workflow-management.name" . }}
    helm.sh/chart: {{ include "workflow-management.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "workflow-management.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "workflow-management.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "workflow-management.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.spring_profiles_active | quote }}
            - name: SERVER_PORT
              value: {{ .Values.appConfig.port | quote }}
            - name: NEXTFLOW_K8S_RUNASUSER
              value: {{ .Values.appConfig.nextflow_k8s_runAsUser | quote }}
            - name: NEXTFLOW_K8S_IMAGEPULLPOLICY
              value: {{ .Values.appConfig.nextflow_k8s_imagePullPolicy | quote }}
            - name: NEXTFLOW_K8S_PLUGINSDIR
              value: {{ .Values.appConfig.nextflow_k8s_pluginsDir | quote }}
            - name: NEXTFLOW_K8S_SERVICEACCOUNT
              value: {{ include "workflow-management.wesServiceAccountName" . }}
            - name: NEXTFLOW_K8S_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: NEXTFLOW_K8S_RUNNAMESPACE
              value: {{ include "workflow-management.wesNamespace" . }}
            - name: NEXTFLOW_K8S_MASTERURL
              value: {{ .Values.appConfig.nextflow_k8s_masterUrl | quote }}
            - name: NEXTFLOW_K8S_TRUSTCERTIFICATE
              value: {{ .Values.appConfig.nextflow_k8s_trust_certificate | quote }}
            - name: NEXTFLOW_WEBLOGURL
              value: {{ .Values.appConfig.nextflow_weblog_url | quote }}
            {{- range $i, $value := .Values.appConfig.nextflow_k8s_volmounts}}
            - name: NEXTFLOW_K8S_VOLMOUNTS_{{$i}}
              value: {{ $value | quote }}
            {{- end }}
            {{- if (contains "apiKey" .Values.appConfig.spring_profiles_active) }}
            - name: SECRET_APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.secret_apikey_ref.name }}
                  key: {{ .Values.appConfig.secret_apikey_ref.key }}
            {{- end }}
            {{- if (contains "secure" .Values.appConfig.spring_profiles_active) }}
            - name: AUTH_JWTPUBLICKEYURL
              value: {{ .Values.appConfig.auth_jwtpublickeyurl }}
            {{- end }}
            {{- if (contains "oauth2Token" .Values.appConfig.spring_profiles_active) }}
            - name: SECRET_CLIENTID
              value: {{ .Values.appConfig.client_id}}
            - name: SECRET_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "workflow-management.fullname" . }}
                  key: client-secret
            - name: SECRET_TOKENURI
              value: {{ .Values.appConfig.auth_token_uri }}  
            {{- end }}
            - name: RABBIT_ENDPOINTS_STANDALONE_HOST
              value: {{ .Values.appConfig.rabbitHost }}
            {{- if (contains "gatekeeper" .Values.appConfig.spring_profiles_active) }}
            - name: SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
              value: {{ .Values.appConfig.kafkaBrokers }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.appConfig.gatekeeperDbUrl }}
            {{- end }}
          {{- if .Values.env }}
            {{ range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.envYaml }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
