{{- if .Values.kubeConfig.app.roleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "workflow-management.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "workflow-management.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}

{{- if .Values.kubeConfig.wes.roleBinding.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "workflow-management.wesRoleBindingName" . }}
  namespace: {{ template "workflow-management.wesNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "workflow-management.wesServiceAccountName" . }}
    namespace: {{ template "workflow-management.wesNamespace" . }}
  - kind: ServiceAccount
    name: {{ template "workflow-management.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
