apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "workflow-management.fullname" . }}
  namespace: {{ template "workflow-management.wesNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "workflow-management.serviceAccountName" . }}
    namespace: {{ template "workflow-management.wesNamespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "workflow-management.fullname" . }}-wes
  namespace: {{ template "workflow-management.wesNamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "workflow-management.wesServiceAccountName" . }}
    namespace: {{ template "workflow-management.wesNamespace" . }}
