{{- if .Values.kubeConfig.wes.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "workflow-management.wesServiceAccountName" . }}
  namespace: {{ template "workflow-management.wesNamespace" . }}
  labels:
{{ include "workflow-management.labels" . | nindent 4 }}
{{- end -}}
