{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow-management.serviceAccountName" . }}
# rtisma: TODO: might need to change name space to .Values.wes.namespace
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "workflow-management.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow-management.serviceAccountName" . }}
  namespace: {{ template "workflow-management.wesNamespace" . }}
  labels:
{{ include "workflow-management.labels" . | nindent 4 }}
{{- end -}}
