{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow-management.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "workflow-management.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workflow-management.wesServiceAccountName" . }}
  namespace: {{ .Values.wes.namespace }}
  labels:
{{ include "workflow-management.labels" . | nindent 4 }}
{{- end -}}
