apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgres.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "postgres.name" . }}
    helm.sh/chart: {{ include "postgres.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresPassword | b64enc | quote }}