dependencies:
  - name: vault
    alias: vaultchart
    repository: https://helm.releases.hashicorp.com
    version: 0.17.1
  - name: consul
    alias: consulchart
    repository: https://helm.releases.hashicorp.com
    version: 0.38.0
