dependencies:
  - name: vault
    alias: vaultchart
    repository: https://helm.releases.hashicorp.com
    version: 0.20.1
  - name: consul
    alias: consulchart
    repository: https://helm.releases.hashicorp.com
    version: 0.46.1
