dependencies:
  - name: vault
    alias: vaultchart
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: 0.19.0
  - name: etcd
    alias: etcdchart
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: 0.6.3