dependencies:
  - name: vault
    alias: vaultchart
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: 0.23.4
  - name: etcd
    alias: etcdchart
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    version: 0.7.3