apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "ego.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ego.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ego.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GOOGLE_CLIENT_IDS
              value: {{ .Values.appConfig.googleClientID }}
            - name: LINKEDIN_CLIENTID
              value: {{ .Values.appConfig.linkedInClientID }}
            - name: LINKEDIN_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: linkedin-client-secret
            - name: LINKEDIN_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/oauth/linkedin-cb"
            - name: GITHUB_CLIENTID
              value: {{ .Values.appConfig.githubClientID }}
            - name: GITHUB_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}
                  key: github-client-secret
            - name: GITHUB_REDIRECTURI
              value: "https://{{ .Values.appConfig.host }}/oauth/github-cb"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ego.fullname" . }}-postgres
                  key: postgres-password
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://{{ template "ego.fullname" . }}-postgres:5432/{{ .Values.postgres.postgresDb }}?stringtype=unspecified"
            - name: SPRING_FLYWAY_ENABLED
              value: "true"
            - name: SPRING_FLYWAY_LOCATIONS
              value: "filesystem:/usr/src/flyway-migration-sql,classpath:db/migration"
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.uiImage.repository }}:{{ .Values.uiImage.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REACT_APP_API
              value: "https://{{ .Values.appConfig.host }}/api"
            - name: REACT_APP_FACEBOOK_APP_ID
              value: {{ .Values.appConfig.reactAppFacebookAppID | quote }}
            - name: REACT_APP_GOOGLE_APP_ID
              value: {{ .Values.appConfig.googleClientID | quote }}
            - name: REACT_APP_DEFAULT_REDIRECT_URI
              value: "https://{{ .Values.appConfig.host }}"
          ports:
            - name: http-ui
              containerPort: 80
              protocol: TCP
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
