apiVersion: v1
kind: Service
metadata:
  name: {{ include "ego.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    helm.sh/chart: {{ include "ego.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 81
      targetPort: http-ui
      protocol: TCP
      name: http-ui
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "ego.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
