dependencies:
  - name: ego
    alias: ego
    repository: https://overture-stack.github.io/charts-server/ 
    version: 0.2.0
  - name: mailhog
    alias: mailhog
    repository: https://icgc-argo.github.io/charts/   
    version: 3.0.0
  - name: program-service
    alias: program
    repository: https://icgc-argo.github.io/charts/   
    version: 0.2.1
  - name: argo-gateway
    alias: gateway
    repository: https://icgc-argo.github.io/charts/   
    version: 1.0.8
  - name: platform-ui
    alias: ui
    repository: https://icgc-argo.github.io/charts/   
    version: 1.0.16
  - name: mongodb
    alias: lecterndb
    repository: https://kubernetes-charts.storage.googleapis.com
    version: 7.2.3
  - name: mongodb-replicaset
    alias: clinicaldb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 3.9.6
  - name: lectern
    alias: lectern
    repository: https://overture-stack.github.io/charts-server/ 
    version: 0.2.2
  - name: clinical
    alias: clinical
    repository: https://icgc-argo.github.io/charts/   
    version: 0.2.2