apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kship.fullname" . }}
  labels:
    {{- include "kship.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kship.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kship.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "kship.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
{{- if .Values.secrets }}
  {{- range $key, $value := .Values.secrets }}
          - name: {{ $value }}
            valueFrom:
              secretKeyRef:
                name: {{ if $.Values.existingSecret }}{{ $.Values.existingSecret }}{{- else }}{{ template "kship.fullname" $ }}{{- end }}
                key: {{ $key }}
  {{- end }}
{{- end }}

{{- if .Values.extraEnv }}
  {{ range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
  {{- end }}
{{- end }}
          ports:
            - name: http
              containerPort: 3518
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
