{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kship.serviceAccountName" . }}
  labels:
{{ include "kship.labels" . | nindent 4 }}
{{- end -}}
