apiVersion: v1
kind: Secret
metadata:
  name: {{ include "song.fullname" . }}
  labels:
    app: {{ include "song.name" . }}
    chart: {{ include "song.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
{{- if .Values.backup.enabled }}
  aws-secret-key: {{ .Values.backup.awsSecretKey | b64enc | quote }}
{{- end }}
  id-authtoken: {{ .Values.appConfig.id.authToken | b64enc | quote }}
  auth-server-client-secret: {{ .Values.appConfig.auth.server.clientSecret | b64enc | quote }}
