{{- if .Values.ingress.enabled -}}
{{- $fullName := include "..fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "..name" . }}
    helm.sh/chart: {{ include "..chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /static/admin
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /admin
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /api
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: http-ui
{{- end }}
