apiVersion: v1
kind: Service
metadata:
  name: {{ include "clinical.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "clinical.name" . }}
    helm.sh/chart: {{ include "clinical.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clinical.port }}
      targetPort: {{ .Values.service.clinical.targetPort }}
      protocol: TCP
      name: {{ .Values.service.clinical.portName }}
    - port: {{ .Values.service.clinicalGql.port }}
      targetPort: {{ .Values.service.clinicalGql.targetPort }}
      protocol: TCP
      name: {{ .Values.service.clinicalGql.portName }}
  selector:
    app.kubernetes.io/name: {{ include "clinical.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
