
{{- if .Values.podsecuritypolicy.enabled -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.rabbit.name }}-{{ .Release.Namespace }}
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
      - "CHOWN"
      - "FOWNER"
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
  - persistentVolumeClaim
  - emptyDir
  - downwardAPI
  - projected
{{- end }}
