apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbit.name }}
spec:
  replicas: {{ .Values.rabbit.replicas }}
  override:
    statefulSet:
      metadata:
        labels:
          rabbitmq: workflow-graph
