apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbit.name }}
spec:
  override:
    statefulSet:
      metadata:
        labels:
          rabbitmq: workflow-graph
  replicas: {{ .Values.rabbit.replicas }}
  {{- if eq .Values.rabbit.additionalConfigEnabled "true" }}
  rabbitmq:
    additionalConfig: {{- .Values.rabbit.additionalConfig | toYaml | indent 4 }}
  {{- end }}
