apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rabbit.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.rabbit.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rabbit.name }}-rabbitmq-server
  namespace: rdpc-collab-dev
