# Default values for platform-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: icgcargo/platform-ui
  tag: 1.0.8
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-qa
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
  host: platform-ui.qa.cancercollaboratory.org
  tls:
    - secretName: platform-ui-tls-cert
      hosts:
        - platform-ui.qa.cancercollaboratory.org

deployment:
  livenessProbe:
    initialDelaySeconds: 120
  readinessProbe:
    initialDelaySeconds: 120

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

appConfig:
  API_ROOT: https://argo-gateway.qa.cancercollaboratory.org
  NODE_PATH: ./
  NODE_ENV: production
  EGO_API_ROOT: https://ego.qa.cancercollaboratory.org
  EGO_CLIENT_ID: platform-ui-qa
