apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibana.name }}
spec:
  version: {{ .Values.kibana.version }}
  count: 1
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
  config:
     xpack.apm.enabled: false
     monitoring.enabled: false