apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "kibana.fullname" . }}-{{ .Release.Namespace }}
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
  - persistentVolumeClaim
  - emptyDir
  - downwardAPI
