image:
  name: ghcr.io/icgc-argo/daco2ego:latest
  pullPolicy: IfNotPresent

# Run at 1:00 AM
schedule: 0 1 * * *

extraEnv:
  {}
  # PROCESS_VAR: abc
extraEnvYaml: []
# - name: EXAMPLE
#   valueFrom:
#     secretKeyRef:
#       name: secret-name
#       key: secret-key

affinity: {}
authDelegator:
  enable: false

configFileContent: "{}"
extraLabels: {}
fullnameOverride: ''
nameOverride: ''
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: true
  name: daco2ego
