# Default values for program-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: icgcargo/daco2ego
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081
  portName: http

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  # className: private
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

extraEnv: {}

nodeSelector: {}

tolerations: []

affinity: {}
volume:
  mountPath: "/daco2ego/files"

rbac:
  create:
    # for vault kubernetes integration
    tokenReview: true
