apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pensato.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pensato.name" . }}
    helm.sh/chart: {{ include "pensato.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ego-client-id: {{ .Values.ego.clientId | b64enc | quote }}
  ego-client-secret: {{ .Values.ego.clientSecret | b64enc | quote }}
