apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pensato.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pensato.name" . }}
    helm.sh/chart: {{ include "pensato.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ include "pensato.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pensato.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pensato.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: ego,localdir
            - name: fs_localDir
              value: /var/lib/pensato/data
            - name: auth_ego_clientId
              valueFrom:
                secretKeyRef:
                  name: {{ include "pensato.fullname" . }}
                  key: ego-client-id
            - name: auth_ego_clientSecret
              valueFrom:
                secretKeyRef:
                  name: {{ include "pensato.fullname" . }}
                  key: ego-client-secret
            - name: auth_ego_introspectionUri
              value: {{ .Values.ego.introspectionUri}}
            - name: auth_ego_userInfoUri
              value: {{ .Values.ego.userInfoUri}}
            - name: auth_ego_scopes
              value: {{ .Values.ego.scopes}}
          ports:
            - name: sftp
              containerPort: 2222
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 240
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
              
          volumeMounts:
            - name: data
              mountPath: /var/lib/pensato/data
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  volumeClaimTemplates:
    - metadata:
       name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
