rabbit:
  name: wfg-rabbit
  replicas: 1

service:
  type: ClusterIP
  port: 5672
  portName: amqp

ingress:
 # className: private
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
  # cert-manager.io/cluster-issuer: clusterissuer-example
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}

tolerations: []
