rabbit:
  name: wfg-rabbit
  replicas: 1
  additionalConfigEnabled: "false"
  additionalConfig: |
    # rabbit-operator config params go here
    # Examples: https://www.rabbitmq.com/kubernetes/operator/using-operator.html
service:
  type: ClusterIP
  port: 5672
  portName: amqp

ingress:
 # className: private
  enabled: false
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  annotations:
  # cert-manager.io/cluster-issuer: clusterissuer-example
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}
podsecuritypolicy:
  enabled: false
tolerations: []
