apiVersion: v1
kind: Service
metadata:
  name: {{ include "score.fullname" . }}
  labels:
    app: {{ include "score.name" . }}
    chart: {{ include "score.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "score.name" . }}
    release: {{ .Release.Name }}
