 apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "song-search.fullname" . }}
  labels:
    {{- include "song-search.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "song-search.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "song-search.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "song-search.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.appConfig.PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.PORT }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.appConfig.PORT }}
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 3
            failureThreshold: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.appConfig.PORT | quote }}
            - name: ELASTIC_HOST
              value: {{ .Values.appConfig.ELASTIC_HOST | quote }}
            - name: ELASTIC_PORT
              value: {{ .Values.appConfig.ELASTIC_PORT | quote }}
            - name: ELASTIC_USEHTTPS
              value: {{ .Values.appConfig.ELASTIC_USEHTTPS | quote }}
            - name: ELASTIC_USEAUTHENTICATION
              value: {{ .Values.appConfig.ELASTIC_USEAUTHENTICATION | quote }}
            {{- if .Values.appConfig.ELASTIC_USEAUTHENTICATION }}
            - name: ELASTIC_USERNAME
              value: {{ .Values.appConfig.ELASTIC_USERNAME | quote }}
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appConfig.ELASTIC_SECRET.name }}
                  key: {{ .Values.appConfig.ELASTIC_SECRET.key }}
            {{- end }}
            - name: ELASTIC_ANALYSIS_CENTRIC_INDEX
              value: {{ .Values.appConfig.ELASTIC_ANALYSIS_CENTRIC_INDEX | quote }}
            - name: ELASTIC_FILE_CENTRIC_INDEX
              value: {{ .Values.appConfig.ELASTIC_FILE_CENTRIC_INDEX | quote }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.appConfig.SPRING_PROFILES_ACTIVE | quote }}
            - name: AUTH_JWTPUBLICKEYURL
              value: {{ .Values.appConfig.AUTH_JWTPUBLICKEYURL | quote }}
          {{- if .Values.env }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
