# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/overture-stack/pensato
  tag: 35b2f48
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ego:
  clientId: ""
  clientSecret: ""
  introspectionUri: ""
  userInfoUri: ""
  scopes: PENSATO.WRITE

persistence:
 size: 1Gi