# Default values for song.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/song
  tag: 1.2.0-alpine
  pullPolicy: IfNotPresent

backupImage:
  repository: overture/song-postgres-backup-s3
  tag: 0.1.6
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-prod-staging
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - song.staging.cancercollaboratory.org
  tls:
    - secretName: ego-staging-cert
      hosts:
        - song.staging.cancercollaboratory.org

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumeSize: 20Gi

appConfig:
  id:
    idURL: https://id.icgc.org
    authToken: "123" #
    realIDs: true
  auth:
    server:
      prefix: pdc
      url: https://auth.icgc.org/oauth/check_token
      clientID: metadata
      clientSecret: test
  dccStorage:
    url: https://storage.cancercollaboratory.org

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: song

backup:
  enabled: false
  schedule: "1 * * * *"
  dbName: song
  awsAccessKey: #
  awsSecretKey: #
  endpointURL: "https://object.cancercollaboratory.org:9080"
