apiVersion: batch/v1
kind: CronJob

metadata:
  name: {{ include "cron-job.fullname" . }}
  labels:
    {{- include "cron-job.labels" . | nindent 4 }}
    {{- include "cron-job.customLabels" . | nindent 4 }}

spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cron-job.labels" . | nindent 12 }}
            {{- include "cron-job.customLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "cron-job.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{.Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            {{- if .Values.execute.enable }}
              {{- with .Values.execute.spec }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
            {{- end }}
            securityContext:
              runAsUser: 1000
            {{- if .Values.persistence.volume.attach }}
            volumeMounts:
              - mountPath: {{.Values.persistence.volume.path }}
                name: {{.Values.persistence.volume.name }}
            {{- end }}
            env:
{{- if .Values.extraEnv }}
  {{- range $key, $value := .Values.extraEnv }}
              - name: {{ $key }}
                value: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- with .Values.extraEnvYaml }}
              {{- toYaml . | nindent 14 }}
{{- end }}
          restartPolicy: {{ .Values.restartPolicy }}
          imagePullSecrets:
            - name: artifactory
          {{- if .Values.persistence.volume.attach }}
          volumes:
            - name: {{.Values.persistence.volume.name }}
              persistentVolumeClaim:
                claimName: {{.Values.persistence.volume.name }}
          {{- end }}


