{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stateless-svc.serviceAccountName" . }}
  labels:
    {{- include "stateless-svc.labels" . | nindent 4 }}
    {{- include "stateless-svc.customLabels" . | nindent 4 }}
{{- end -}}
