{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "workflow-graph-manager.roleBindingName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "workflow-graph-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "workflow-graph-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
