# Default values for ego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/ego
  tag: 20181221-alpine
  pullPolicy: IfNotPresent

uiImage:
  repository: overture/ego-ui
  tag: "2019010310"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-prod-staging
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: ego.staging.cancercollaboratory.org
  tls:
    - secretName: ego-staging-cert
      hosts:
        - ego.staging.cancercollaboratory.org

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: ego

appConfig:
  # api configs
  activeProfiles: auth
  host: ego.staging.cancercollaboratory.org
  googleClientID:
  googleClientSecret:
  linkedInClientID:
  linkedInClientSecret:
  githubClientID:
  githubClientSecret:
  swaggerHost:
  swaggerBaseUrl:
  # ui configs
  reactAppFacebookAppID:
