apiVersion: v1
kind: Secret
metadata:
  name: {{ template "icgc-legacy-sftp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "icgc-legacy-sftp.name" . }}
    helm.sh/chart: {{ include "icgc-legacy-sftp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}