{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "icgc-legacy-sftp.serviceAccountName" . }}
  labels:
    {{- include "icgc-legacy-sftp.labels" . | nindent 4 }}
    {{- include "icgc-legacy-sftp.customLabels" . | nindent 4 }}
{{- end -}}
