# Default values for score.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: overture/score-server
  tag: test
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/issuer: letsencrypt-prod-staging
  hosts:
    - score.staging.cancercollaboratory.org
      
  tls:
    - secretName: letsencrypt-prod-score-qa-key
      hosts:
        - score.qa.cancercollaboratory.org
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

appConfig:
  authServer:
    clientID: 3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
    clientSecret: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
    URL: http://localhost:8084/check_token/
  objectStorage:
    accessKey: minio
    secretKey: minio123
    URL: http://localhost:8085
  serverUrl: http://localhost:8080
  storageServer:
    dataBucket: oicr.icgc.test
    dataDir: data
    JMXPort: "10018"
    sentinel: heliograph
    port: "8087"
    stateBucket: oicr.icgc.test
