apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "es-operator.fullname" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - {{ include "es-operator.fullname" . }}-{{ .Release.Namespace }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
