# Default values for program-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: icgcargo/program-service
  tag: 97d9e46
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: false
  annotations:
    # certmanager.k8s.io/acme-challenge-type: dns01
    # certmanager.k8s.io/acme-dns01-provider: route53
    # certmanager.k8s.io/cluster-issuer: letsencrypt-prod-qa
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  hosts:
    - program-service.someplace
  tls:
    - secretName: program-service-someplace-cert
      hosts:
        - program-service.someplace

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

extraEnv: {}

nodeSelector: {}

tolerations: []

affinity: {}

postgres:
  postgresUsername: postgres
  postgresPassword: password
  postgresDb: program_service
