# Default values for workflow-graph-ingest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/icgc-argo/workflow-graph-ingest-node
  pullPolicy: Always
  tag: "0.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsGroup: 9999
  runAsNonRoot: true
  runAsUser: 9999

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


resources:
  requests:
    memory: "512Mi"
    cpu: "1"
  limits:
    memory: "1024Mi"
    cpu: "2"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

appConfig:
  port: 8082
  rabbitHost: # fill me in!
  kafkaBrokers: # fill me in!

wfgConfig:
  pipelineId: # fill me in!
  nodeId: # fill me in!

extraEnv:
  SPRING_CLOUD_STREAM_BINDINGS_INBOUND_DESTINATION: wfg-test
  SPRING_CLOUD_STREAM_KAFKA_BINDINGS_INBOUND_CONSUMER_ENABLEDLQ: true
  SPRING_CLOUD_STREAM_KAFKA_BINDINGS_INBOUND_CONSUMER_DLQNAME: wfg-test-dql

extraEnvYaml:
  - name: SPRING_RABBITMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: # fill me in!
        key: username
  - name: SPRING_RABBITMQ_PASSWORD
    valueFrom:
        secretKeyRef:
          name: # fill me in!
          key: password
